//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangXachTay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int idContact { get; set; }
        public string chuDe { get; set; }
        public string tieuDe { get; set; }
        public string noiDung { get; set; }
        public string hoTen { get; set; }
        public string email { get; set; }
        public string sdt { get; set; }
        public Nullable<System.DateTime> thoiGianGui { get; set; }
        public Nullable<bool> trangThai { get; set; }
        public string traLoi { get; set; }
        public Nullable<System.DateTime> thoigianTraLoi { get; set; }
        public string ghiChu { get; set; }
    }
}
