//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangXachTay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablePRODUCT
    {
        public int idSP { get; set; }
        public string loaiSP { get; set; }
        public string tenSP { get; set; }
        public Nullable<int> dongiaSP { get; set; }
        public Nullable<int> soluongSP { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public string nhacungcap { get; set; }
        public byte[] img { get; set; }
        public string ghichuSP { get; set; }
    }
}
