//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangXachTay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
<<<<<<< HEAD
    
    public partial class tableCUSTOMER
    {
        [Display(Name = "Id khách hàng")]
=======

    public partial class tableCUSTOMER
    {
        [Display(Name = "ID khách hàng")]
>>>>>>> 1d0d995bd84c21fcb9a5a25c3f6bfd9ec178fc81
        public int idKH { get; set; }
        [Display(Name = "Tên khách hàng")]
        public string tenKH { get; set; }
        [Display(Name = "Giới tính")]
        public string gioitinh { get; set; }
        [Display(Name = "Số điện thoại")]
        public string sodienthoaiKH { get; set; }
        [Display(Name = "Địa chỉ")]
        public string diachi { get; set; }
        [Display(Name = "Ghi chú")]
        public string ghichu { get; set; }
    }
}
