//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangXachTay.Models
{
    using System;
    using System.Collections.Generic;
<<<<<<< HEAD
    
    public partial class tableBILL
    {
        public int idHD { get; set; }
        public int idKH { get; set; }
=======
    using System.ComponentModel.DataAnnotations;

    public partial class tableBILL
    {
        [Display(Name = "ID hóa đơn")]
        public int idHD { get; set; }
        [Display(Name = "Mã khách hàng")]
        public Nullable<int> idKH { get; set; }
        [Display(Name = "Tên khách hàng")]
>>>>>>> d963beb610f3b4bccc159092b5073806d70c9f60
        public string tenKH { get; set; }
        public string sodienthoaiKH { get; set; }
        public Nullable<System.DateTime> ngaydathang { get; set; }
        public Nullable<System.DateTime> ngaygiaohang { get; set; }
        public Nullable<System.DateTime> ngaynhanhang { get; set; }
        public string diachinhanhang { get; set; }
        public Nullable<int> idSP { get; set; }
        public string tenSP { get; set; }
        public Nullable<int> dongiaSP { get; set; }
        public Nullable<int> soluongSP { get; set; }
        public string ghichuSP { get; set; }
        public Nullable<int> thanhtienBILL { get; set; }
        public Nullable<int> soluongBILL { get; set; }
        public Nullable<int> dongiaBILL { get; set; }
        public Nullable<int> tongdoanhthu { get; set; }
<<<<<<< HEAD
=======
        [Display(Name = "Bill-Ghi chú")]

>>>>>>> d963beb610f3b4bccc159092b5073806d70c9f60
        public string ghichuBILL { get; set; }
    }
}
