//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangXachTay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tablePRODUCT
    {
<<<<<<< HEAD
        [Display (Name= "Mã Sản Phẩm")]
        [Required]
=======
        [Display(Name = "ID sản phẩm")]
>>>>>>> d963beb610f3b4bccc159092b5073806d70c9f60
        public int idSP { get; set; }
        [Display(Name = "Loại Sản Phẩm")]
        [Required]
        public string loaiSP { get; set; }
        [Display(Name = "Tên Sản Phẩm")]
        [Required]
        public string tenSP { get; set; }
        [Display(Name = "Đơn Giá")]
        [Required]
        public Nullable<int> dongiaSP { get; set; }
        [Display(Name = "Số Lượng")]
        [Required]
        public Nullable<int> soluongSP { get; set; }
        [Display(Name = "Ngày Nhập")]
        [Required]
        public Nullable<System.DateTime> ngaynhap { get; set; }
        [Display(Name = "Nhà Cung Cấp")]
        [Required]
        public string nhacungcap { get; set; }
        [Display(Name = "Hình Ảnh")]
        [Required]
        public byte[] img { get; set; }
<<<<<<< HEAD
        [Display(Name = "Ghi Chú")]
        [Required]
=======
        [Display(Name = "Ghi chú")]

>>>>>>> d963beb610f3b4bccc159092b5073806d70c9f60
        public string ghichuSP { get; set; }
    }
}
