//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangXachTay
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tableTTSP
    {
        [Display(Name = "ID")]
        public int idSP { get; set; }
        [Display(Name = "Mã Sản Phẩm")]
        public string maSP { get; set; }
        [Display(Name = "Tên Sản Phẩm")]
        public string tenSP { get; set; }
        [Display(Name = "Giá")]
        public int dongia { get; set; }
        [Display(Name = "Số Lượng")]
        public Nullable<int> soluong { get; set; }
        [Display(Name = "Ngày Nhập")]
        public System.DateTime ngaynhap { get; set; }
        [Display(Name = "Ghi Chú")]
        public string ghichu { get; set; }
    }
}
