//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangXachTay
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableTTHD
    {
        public int idHD { get; set; }
        public string maKH { get; set; }
        public string tenKH { get; set; }
        public string sodienthoaiKH { get; set; }
        public Nullable<System.DateTime> ngaydathang { get; set; }
        public Nullable<System.DateTime> ngaynhanhang { get; set; }
        public string diachinhanhang { get; set; }
        public string maSP { get; set; }
        public string tenSP { get; set; }
        public Nullable<int> dongia { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> thanhtien { get; set; }
        public string ghichu { get; set; }
    }
}
