//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangXachTay
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableTTKH
    {
        public int idKH { get; set; }
        public string maKH { get; set; }
        public string tenKH { get; set; }
        public string gioitinh { get; set; }
        public string sodienthoaiKH { get; set; }
        public string diachi { get; set; }
        public string ghichu { get; set; }
    }
}
